name: mockito
version: 4.1.2

description: A mock framework inspired by Mockito.
homepage: https://github.com/dart-lang/mockito

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.15
  build: ^1.3.0
  code_builder: ^3.4.0
  collection: ^1.1.0
  dart_style: ^1.3.6
  matcher: ^0.12.3
  meta: ^1.3.0-nullsafety
  source_gen: ^0.9.6
  test_api: ^0.2.19-nullsafety

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.1.0
  build_web_compilers: '>=1.0.0 <3.0.0'
  pedantic: ^1.10.0-nullsafety
  test: ^1.5.1

dependency_overrides:
  async: ^2.5.0-nullsafety
  boolean_selector: ^2.1.0-nullsafety
  build_resolvers: ^1.3.10
  charcode: ^1.2.0-nullsafety
  matcher: ^0.12.10-nullsafety
  path: ^1.8.0-nullsafety
  pedantic: ^1.10.0-nullsafety
  source_span: ^1.8.0-nullsafety
  stack_trace: ^1.10.0-nullsafety
  stream_channel: ^2.1.0-nullsafety
  string_scanner: ^1.1.0-nullsafety
  term_glyph: ^1.2.0-nullsafety
  test_api: ^0.2.19-nullsafety
